matrix:
  include:
    - language: node_js
      name: 'GoCryptoTrader [front-end]'
      node_js:
        - '10'
        - '8'
        - '6'
      before_install:
        - cd web/
      install:
        - npm install
      script:
        - npm run lint
        - npm run build

    - language: go
      dist: xenial
      name: 'GoCryptoTrader [back-end] [linux]'
      go:
        - 1.12.x
      env:
        - GO111MODULE=on
      install: true
      cache:
        directories:
          - $GOPATH/pkg/mod

      script:
        - make check
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - language: go
      os: osx
      name: 'GoCryptoTrader [back-end] [darwin]'
      go:
        - 1.12.x
      env:
        - GO111MODULE=on
      install: true
      cache:
        directories:
          - $GOPATH/pkg/mod
      
      script:
        - make check
      after_success:
        - bash <(curl -s https://codecov.io/bash)
